<ModuleDefinition
	ModuleId="FPSPlayer"
	VersionId="1"
	Description="Starter module for FPS gameplay."
	ScriptFile="FPSPlayer"
	CreateFunction="onCreate"
	DestroyFunction="onDestroy"
	Group="Game"
    Dependencies="UI=1"
    Priority="2.0">
	<DeclaredAssets
        canSave="true"
        canSaveDynamicFields="true"
        Extension="asset.taml"
        Recurse="true" />
</ModuleDefinition>